name: Deploy to GitHub Pages (official actions)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
          # make the artifact name unique per run to avoid duplicate-name collisions
          artifact_name: github-pages-${{ github.run_id }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # must match the artifact_name above
          artifact_name: github-pages-${{ github.run_id }}
